# Generated by Django 4.1 on 2022-08-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=220)),
                ('nationality', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
                ('editorial', models.DateField(verbose_name='Editorial')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('author', models.ManyToManyField(to='books.author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
            },
        ),
    ]
