# Generated by Django 4.1 on 2022-08-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Cover'),
        ),
    ]
