# Generated by Django 4.1 on 2022-08-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='editorial',
            field=models.CharField(max_length=100, verbose_name='Editorial'),
        ),
    ]
